In [1]:
import pandas as pd

# Load the CSV file into a DataFrame
df = pd.read_csv('/content/raksha-farmer-query.csv')

# Display the first few rows to understand the data structure
print("Original DataFrame head:")
display(df.head())

Original DataFrame head:

,StateName,DistrictName,BlockName,Season,Sector,Category,Crop,QueryType,QueryText,CreatedOn,year,month
0,KARNATAKA,HUBBALLI,PUSAD,NaN,HORTICULTURE,Others,Others,Market,Farmer asked about sowing time of Onion?,2025-03-20T06:45:00,2025,3
1,MAHARASHTRA,AKOLA,SAKOLI,NaN,HORTICULTURE,Others,Others,Market,FARMER ASKED ABOUT FERTILIZER DOSES FOR CITRUS...,2025-03-08T02:35:00,2025,3
2,MAHARASHTRA,LATUR,PUSAD,NaN,AGRICULTURE,Others,Others,Market,FARMER ASKED ABOUT CONTROL OF BLIGHT ATTACK ON...,2025-02-03T08:13:00,2025,2
3,UTTAR PRADESH,LUCKNOW,SAKOLI,NaN,HORTICULTURE,Others,Others,Market,FARMER ASKED ABOUT FARMER ID CARD PROBLEM?,2025-03-10T02:44:00,2025,3
4,MAHARASHTRA,LATUR,PAUNI,NaN,AGRICULTURE,Others,Others,Market,Farmer asked about irrigation schedule for Onion?,2025-02-02T11:51:00,2025,2

Now, let's define the keywords for each category and create a function to classify the queries.

In [4]:
def classify_query(query_text):
    query_text = str(query_text).lower()

    if any(keyword in query_text for keyword in ['rain', 'weather', 'storm', 'drought', 'cyclone', 'temperature', 'humidity']):
        return 'Weather'
    elif any(keyword in query_text for keyword in ['pest', 'insect', 'disease', 'fungus', 'bug', 'aphid', 'control']):
        return 'Pest'
    elif any(keyword in query_text for keyword in ['nutrient', 'fertilizer', 'soil', 'deficiency', 'urea', 'potash', 'phosphorus']):
        return 'Nutrient'
    elif any(keyword in query_text for keyword in ['market', 'price', 'sell', 'buy', 'demand', 'supply', 'trade', 'export']):
        return 'Market'
    elif any(keyword in query_text for keyword in ['scheme', 'subsidy', 'government', 'loan', 'grant', 'policy', 'pm kisan']):
        return 'Government Scheme'
    else:
        return 'Other'

# Apply the classification function to the 'QueryText' column
df['Predicted_Category'] = df['QueryText'].apply(classify_query)

# Display the DataFrame with the new 'Predicted_Category' column
print("\nDataFrame with classified queries:")
display(df.head(10))

DataFrame with classified queries:

,StateName,DistrictName,BlockName,Season,Sector,Category,Crop,QueryType,QueryText,CreatedOn,year,month,Predicted_Category
0,KARNATAKA,HUBBALLI,PUSAD,NaN,HORTICULTURE,Other,Others,Market,Farmer asked about sowing time of Onion?,2025-03-20T06:45:00,2025,3,Other
1,MAHARASHTRA,AKOLA,SAKOLI,NaN,HORTICULTURE,Nutrient,Others,Market,FARMER ASKED ABOUT FERTILIZER DOSES FOR CITRUS...,2025-03-08T02:35:00,2025,3,Nutrient
2,MAHARASHTRA,LATUR,PUSAD,NaN,AGRICULTURE,Pest,Others,Market,FARMER ASKED ABOUT CONTROL OF BLIGHT ATTACK ON...,2025-02-03T08:13:00,2025,2,Pest
3,UTTAR PRADESH,LUCKNOW,SAKOLI,NaN,HORTICULTURE,Other,Others,Market,FARMER ASKED ABOUT FARMER ID CARD PROBLEM?,2025-03-10T02:44:00,2025,3,Other
4,MAHARASHTRA,LATUR,PAUNI,NaN,AGRICULTURE,Other,Others,Market,Farmer asked about irrigation schedule for Onion?,2025-02-02T11:51:00,2025,2,Other
5,UTTAR PRADESH,LUCKNOW,SAKOLI,NaN,AGRICULTURE,Weather,Others,Market,Farmer asked about weather impact on Wheat?,2025-01-05T15:51:00,2025,1,Weather
6,KARNATAKA,MYSURU,SAKOLI,NaN,HORTICULTURE,Government Scheme,Others,Plant Protection,FARMER ASKED ABOUT DRIP IRRIGATION SCHEMES ?,2025-02-22T07:15:00,2025,2,Government Scheme
7,KARNATAKA,BELAGAVI,MOHADI,NaN,HORTICULTURE,Nutrient,Others,Market,Farmer asked about nutrient spray for flowerin...,2025-01-11T08:54:00,2025,1,Nutrient
8,MAHARASHTRA,YAVATMAL,SAKOLI,NaN,HORTICULTURE,Government Scheme,Others,Plant Protection,FARMER ASKED ABOUT DRIP IRRIGATION SCHEMES ?,2025-01-24T19:46:00,2025,1,Government Scheme
9,MADHYA PRADESH,BHOPAL,SAKOLI,NaN,HORTICULTURE,Market,Others,Plant Protection,FARMER ASKED ABOUT MARKET RATE OF BENGAL GRAM?,2025-03-23T17:19:00,2025,3,Market

Let's see the distribution of the classified categories.

In [6]:
# Get the value counts of the 'Predicted_Category' column
category_counts = df['Predicted_Category'].value_counts()

# Display the counts
print("\nDistribution of Query Categories:")
print(category_counts)

# Optionally, display as a percentage
print("\nPercentage Distribution of Query Categories:")
print(df['Predicted_Category'].value_counts(normalize=True) * 100)

Distribution of Query Categories:
Predicted_Category
Other                867
Nutrient             316
Pest                 283
Market               278
Government Scheme    131
Weather              125
Name: count, dtype: int64

Percentage Distribution of Query Categories:
Predicted_Category
Other                43.35
Nutrient             15.80
Pest                 14.15
Market               13.90
Government Scheme     6.55
Weather               6.25
Name: proportion, dtype: float64

In [7]:
# Print all column names in the DataFrame
print("All column names in the DataFrame:")
print(df.columns.tolist())

print("\nBased on the initial data and typical naming conventions, 'Category' or 'QueryType' are the most likely candidates for containing the actual category labels (ground truth) for the farmer queries. Please confirm which one, if any, represents the true labels.")

All column names in the DataFrame:
['StateName', 'DistrictName', 'BlockName', 'Season', 'Sector', 'Category', 'Crop', 'QueryType', 'QueryText', 'CreatedOn', 'year', 'month', 'Predicted_Category']

Based on the initial data and typical naming conventions, 'Category' or 'QueryType' are the most likely candidates for containing the actual category labels (ground truth) for the farmer queries. Please confirm which one, if any, represents the true labels.

In [8]:
print("\nUnique values in the original 'Category' column:")
print(df['Category'].unique())

print("\nFirst 10 values of the original 'Category' column:")
print(df['Category'].head(10))

Unique values in the original 'Category' column:
['Other' 'Nutrient' 'Pest' 'Weather' 'Government Scheme' 'Market']

First 10 values of the original 'Category' column:
0                Other
1             Nutrient
2                 Pest
3                Other
4                Other
5              Weather
6    Government Scheme
7             Nutrient
8    Government Scheme
9               Market
Name: Category, dtype: object

Now, let's examine the `QueryType` column.

In [9]:
print("\nUnique values in the 'QueryType' column:")
print(df['QueryType'].unique())

print("\nFirst 10 values of the 'QueryType' column:")
print(df['QueryType'].head(10))

Unique values in the 'QueryType' column:
['Market' 'Plant Protection' 'Nutrient Management' 'Seeds'
 'Government Schemes' 'Weather']

First 10 values of the 'QueryType' column:
0              Market
1              Market
2              Market
3              Market
4              Market
5              Market
6    Plant Protection
7              Market
8    Plant Protection
9    Plant Protection
Name: QueryType, dtype: object